;;;; opencv.import.scm - GENERATED BY CHICKEN 4.8.0.3 -*- Scheme -*-

(eval '(import scheme chicken foreign lolevel))
(##sys#register-compiled-module 'opencv (list) '() (list) (list))

;; END OF FILE
